---
version: "2.0"
services:
  api:
    image: cro7/subtitle_generator_service:0.0.2
    expose:
      - port: 8050
        as: 8050
        to:
          - service: ui
          - global: true
    env:
      - DYNACONF_TRANSCRIBER__MODEL=medium
      - DYNACONF_API__SERVER__BIND=8050
  ui:
    image: cro7/subtitle_generator_ui:0.0.2
    expose:
      - port: 8051
        as: 80
        to:
          - global: true
    env:
      - DYNACONF_API__HOST=api
      - DYNACONF_API__PORT=8050
      - PORT=8051
profiles:
  compute:
    api:
      resources:
        cpu:
          units: 2
        memory:
          size: 5Gi
        storage:
          - size: 10Gi
    ui:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          - size: 5Gi
  placement:
    dcloud:
      pricing:
        api:
          denom: uakt
          amount: 1000
        ui:
          denom: uakt
          amount: 1000
deployment:
  api:
    dcloud:
      profile: api
      count: 1
  ui:
    dcloud:
      profile: ui
      count: 1
