version: '3.5'

services:

  api:
    container_name: subtitle_generator_service_worker
    image: cro7/subtitle_generator_service:0.0.2
    environment:
      DYNACONF_TRANSCRIBER__MODEL: medium
      DYNACONF_API__SERVER__BIND: 8050
    ports:
      - "8050:8050"
  ui:
    container_name: subtitle_generator_ui_worker
    image: cro7/subtitle_generator_ui:0.0.2
    environment:
      DYNACONF_API__HOST: api
      DYNACONF_API__PORT: 8050
      PORT: 8051
    ports:
      - "80:8051"
    depends_on:
      - "api"