default:
  api:
    name: Subtitle generation API
    desc: This is a service for Subtitle generation.
    openapi_file: /openapi.json
    docs_path: /docs
    version: 0.0.1
    server:
      worker_class: uvicorn.workers.UvicornWorker
      workers: 1 # can also be auto
      bind: '8050'
      accesslog: '-'
      graceful_timeout: 1
      timeout: 300000
      reload: True
    endpoints:
      prefix: /subtitle/api/v1
      asr: transcribe
      translate: translate
    cors:
      allow_origins: ['*']
      allow_credentials: True
      allow_methods: ['*']
      allow_headers: ['*']
      max_age: 86400 # 24 hours
  logging:
    level: DEBUG
    format: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <yellow>{process}</yellow> |<level>{level: <8}</level> | <cyan>{name}:<cyan>{extra[classname]}</cyan>:</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
    loggers_to_loguru:
      - gunicorn
      - gunicorn.access
      - gunicorn.error
      - uvicorn
      - uvicorn.access
      - uvicorn.error
  transcriber:
    model: small
    device: cpu
    ckpt_path: checkpoints/whisper
    compute_type: float16
    cpu_threads: 8
    num_workers: 4
    local_files_only: False
    parameters:
      beam_size: 5
      best_of: 5
      temperature: [0.0, 0.2]
      word_timestamps: true
      compression_ratio_threshold: 2.4
      condition_on_previous_text: false
      log_prob_threshold: -0.8
      no_speech_threshold: 0.5
  output_dir: outputs/

development:
  debug: True
  env: development
  server:
    reload: True
    dynaconf_merge: True # to merge default settings

staging:
  debug: False
  env: staging
  server:
    reload: True
    dynaconf_merge: True # to merge default settings
  logging:
    level: INFO
    dynaconf_merge: True

production:
  debug: False
  env: production
  server:
    reload: False
    dynaconf_merge: True # to merge default settings
  logging:
    level: INFO
    format: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <yellow>{process}</yellow> |<level>{level: <8}</level> | <level>{message}</level>"
    dynaconf_merge: True
